function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE result OUTPUT_VARIABLE stdout
                  ERROR_VARIABLE stderr TIMEOUT 30)
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "${ARGV}: ${result}\n${stdout}${stderr}")
  endif()
endfunction()
function(expect_failure expected)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE stdout
                  ERROR_VARIABLE stderr TIMEOUT 30)
  if(result STREQUAL "0" OR NOT "${stdout}${stderr}" MATCHES "${expected}")
    message(FATAL_ERROR "Expected failure '${expected}': ${ARGN}\n${result}\n${stdout}${stderr}")
  endif()
endfunction()

set(out "${WORK}/dispatch")
file(MAKE_DIRECTORY "${out}")
file(READ "${FIXTURES}/dispatch/system.dice" config)
set(flags -std=gnu11 -D_GNU_SOURCE -DDICE_ROLLED=1 -Wall -Wextra -Werror -fPIC "-I${out}"
          "-I${SOURCE}/include" "-I${SOURCE}/src/dice"
          "-I${SOURCE}/deps/libvsync/include")
include("${FIXTURES}/core.cmake")
set(link -pthread ${DL_LIBS})
if(APPLE)
  set(shared -dynamiclib)
  set(plugin_flags -undefined dynamic_lookup)
  set(suffix .dylib)
  set(preload DYLD_INSERT_LIBRARIES)
else()
  set(shared -shared)
  set(suffix .so)
  set(preload LD_PRELOAD)
endif()
set(lib "${out}/runtime${suffix}")
set(mod "${out}/plugin${suffix}")
set(app "${out}/app")
foreach(plugins true false)
  string(REPLACE "(plugins true)" "(plugins ${plugins})" input "${config}")
  file(WRITE "${out}/system.dice" "${input}")
  run("${DICE}" "${out}/system.dice" -o "${out}")
  if(NOT plugins)
    file(READ "${out}/dice.c" source)
    if(source MATCHES "dice_callbacks_|DICE_WEAK DICE_HIDE enum ps_err dice_slot_")
      message(FATAL_ERROR "Sealed runtime contains callback fallbacks")
    endif()
  endif()
  foreach(checked 0 1)
    foreach(lto 0 1)
      set(build_flags ${flags} -DDICE_CHECK_ROUTES=${checked})
      if(lto)
        list(APPEND build_flags -O3 -flto)
      endif()
      run("${CC}" ${build_flags} -c "${out}/dice.c" -o "${out}/dice.o")
      build_core(core_objects "${out}/dice.c" ${build_flags})
      run("${CC}" ${build_flags} -c "${FIXTURES}/dispatch/handlers.c" -o "${out}/handlers.o")
      if(NOT plugins)
        # A single missing consumer must fail the link, even with all others supplied.
        run("${CC}" ${build_flags} -DOMIT_MIDDLE -c
            "${FIXTURES}/dispatch/handlers.c" -o "${out}/partial.o")
        expect_failure("dice_slot_" "${CC}" ${build_flags}
            "${FIXTURES}/dispatch/main.c" "${out}/dice.o" ${core_objects} "${out}/partial.o"
            ${link} -o "${app}")
      endif()
      run("${CC}" ${build_flags} ${shared} ${plugin_flags}
          "${FIXTURES}/dispatch/plugin.c" -o "${mod}")
      foreach(strong 0 1)
        if(NOT plugins AND NOT strong)
          continue()
        endif()
        set(objects "${out}/dice.o" ${core_objects})
        set(env_args)
        if(strong)
          list(APPEND objects "${out}/handlers.o")
          list(APPEND env_args WITH_STRONG=1)
        endif()
        run("${CC}" ${build_flags} ${shared} ${objects} ${link} -o "${lib}")
        run("${CC}" ${build_flags} "${FIXTURES}/dispatch/main.c" "${lib}" ${link} -o "${app}")
        run("${CMAKE_COMMAND}" -E env ${env_args} "${app}")
        if(plugins)
          run("${CMAKE_COMMAND}" -E env ${env_args} "${app}" wildcard)
          run("${CMAKE_COMMAND}" -E env ${env_args} WITH_PLUGIN=1
              "${preload}=${lib}:${mod}" "${app}")
        else()
          expect_failure("subscribe" "${CMAKE_COMMAND}" -E env ${env_args}
              WITH_PLUGIN=1 "${preload}=${lib}:${mod}" "${app}")
        endif()
        foreach(mode zero gap boundary)
          if(checked)
            expect_failure("undeclared consumes" "${app}" "${mode}")
          else()
            run("${app}" "${mode}")
          endif()
        endforeach()
      endforeach()
    endforeach()
  endforeach()
endforeach()
message(STATUS "weak callback fallback, strong override, both pubsub phases and LTO passed")
