function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE result OUTPUT_VARIABLE stdout
                  ERROR_VARIABLE stderr TIMEOUT 30)
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "${ARGV}: ${result}\n${stdout}${stderr}")
  endif()
endfunction()
function(reject)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE result OUTPUT_VARIABLE stdout
                  ERROR_VARIABLE stderr TIMEOUT 30)
  if(result STREQUAL "0" OR NOT "${stdout}${stderr}" MATCHES "undeclared consumes")
    message(FATAL_ERROR "Expected route rejection: ${ARGV}\n${result}\n${stdout}${stderr}")
  endif()
endfunction()

set(out "${WORK}/dispatch")
file(MAKE_DIRECTORY "${out}")
file(READ "${FIXTURES}/dispatch/system.dice" config)
set(flags -std=gnu11 -D_GNU_SOURCE -Wall -Wextra -Werror -fPIC "-I${out}")
set(link -pthread)
if(APPLE)
  set(shared -dynamiclib)
  set(plugin_flags -undefined dynamic_lookup)
  set(suffix .dylib)
  set(preload DYLD_INSERT_LIBRARIES)
else()
  set(shared -shared)
  set(suffix .so)
  set(preload LD_PRELOAD)
  list(APPEND link -ldl)
endif()
set(lib "${out}/runtime${suffix}")
set(mod "${out}/plugin${suffix}")
set(app "${out}/app")
foreach(plugins true false)
  string(REPLACE "(plugins true)" "(plugins ${plugins})" input "${config}")
  file(WRITE "${out}/system.dice" "${input}")
  run("${DICE}" roll "${out}/system.dice" -o "${out}")
  foreach(checked 0 1)
    foreach(lto 0 1)
      set(build_flags ${flags} -DDICE_CHECK_ROUTES=${checked})
      if(lto)
        list(APPEND build_flags -O3 -flto)
      endif()
      run("${CC}" ${build_flags} -c "${out}/dice.c" -o "${out}/dice.o")
      run("${CC}" ${build_flags} -c "${FIXTURES}/dispatch/handlers.c" -o "${out}/handlers.o")
      run("${CC}" ${build_flags} ${shared} ${plugin_flags}
          "${FIXTURES}/dispatch/plugin.c" -o "${mod}")
      foreach(strong 0 1)
        set(objects "${out}/dice.o")
        set(env_args)
        if(strong)
          list(APPEND objects "${out}/handlers.o")
          list(APPEND env_args WITH_STRONG=1)
        endif()
        run("${CC}" ${build_flags} ${shared} ${objects} ${link} -o "${lib}")
        run("${CC}" ${build_flags} "${FIXTURES}/dispatch/main.c" "${lib}" ${link} -o "${app}")
        run("${CMAKE_COMMAND}" -E env ${env_args} "${app}")
        run("${CMAKE_COMMAND}" -E env ${env_args} WITH_PLUGIN=1
            "${preload}=${lib}:${mod}" "${app}")
        foreach(mode zero gap boundary)
          if(checked)
            reject("${app}" "${mode}")
          else()
            run("${app}" "${mode}")
          endif()
        endforeach()
      endforeach()
    endforeach()
  endforeach()
endforeach()
message(STATUS "weak callback fallback, strong override, both pubsub phases and LTO passed")
