# Generated dispatchers link with separately compiled runtime sources.
function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE result OUTPUT_VARIABLE stdout
                  ERROR_VARIABLE stderr TIMEOUT 30)
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "${ARGV}: ${result}\n${stdout}${stderr}")
  endif()
  set(result_text "${stdout}${stderr}" PARENT_SCOPE)
endfunction()
function(expect_failure expected)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE stdout
                  ERROR_VARIABLE stderr TIMEOUT 30)
  if(result STREQUAL "0" OR NOT "${stdout}${stderr}" MATCHES "${expected}")
    message(FATAL_ERROR "Expected failure '${expected}': ${ARGN}\n${result}\n${stdout}${stderr}")
  endif()
endfunction()
function(assert_contains text pattern)
  if(NOT "${text}" MATCHES "${pattern}")
    message(FATAL_ERROR "Missing '${pattern}' in: ${text}")
  endif()
endfunction()


set(root "${WORK}/integration")
set(out "${root}/generated")
file(MAKE_DIRECTORY "${root}")
set(config [=[(dice (schema 1)
  (include "events.dice")
  (include "interceptors.dice")
  (runtime (plugins true))
  (slot first (number 32) (before later)
    (consumes (CHAIN_TEST EVENT_TEST ANY_EVENT))
    (produces (CHAIN_EMPTY EVENT_UNUSED)))
  (slot later (number 40) (after first)
    (consumes (CHAIN_TEST ANY_EVENT))))
]=])
file(COPY "${SOURCE}/examples/roll/interceptors.dice" DESTINATION "${root}")
file(WRITE "${root}/system.dice" "${config}")
# EVENT_TEST and CHAIN_TEST are inferred from slots; explicit IDs are optional.
file(WRITE "${root}/events.dice" "(dice (events (EVENT_UNUSED 200)) (chains (CHAIN_EMPTY 15)))\n")
run("${DICE}" --check "${root}/system.dice")
run("${DICE}" --licenses)
file(READ "${SOURCE}/LICENSE" license)
string(FIND "${result_text}" "${license}" license_position)
if(NOT license_position EQUAL 0)
  message(FATAL_ERROR "Generator did not read the source-tree LICENSE")
endif()
run("${DICE}" "${root}/system.dice" --output "${out}"
    --depfile "${root}/dice.d")
file(READ "${root}/dice.d" dependencies)
foreach(path LICENSE src/cli/templates/call.in src/cli/templates/module.in
             src/cli/templates/public.in)
  string(FIND "${dependencies}" "${SOURCE}/${path}" position)
  if(position LESS 0)
    message(FATAL_ERROR "Missing generator dependency: ${path}")
  endif()
endforeach()
foreach(option --check --query --graph)
  expect_failure("Usage:" "${DICE}" "${option}")
endforeach()
file(SHA256 "${out}/dice.c" c_before)
file(SHA256 "${out}/dice.h" h_before)
run("${DICE}" "${root}/system.dice" --output "${out}")
file(SHA256 "${out}/dice.c" c_after)
file(SHA256 "${out}/dice.h" h_after)
if(NOT c_before STREQUAL c_after OR NOT h_before STREQUAL h_after)
  message(FATAL_ERROR "Non-deterministic generation")
endif()
# A depfile cannot overwrite one half of an existing generated pair.
foreach(extension c h)
  expect_failure("dependency file must differ" "${DICE}"
      "${root}/system.dice" --output "${out}"
      --depfile "${out}/../generated/dice.${extension}")
endforeach()
file(SHA256 "${out}/dice.c" c_after)
file(SHA256 "${out}/dice.h" h_after)
if(NOT c_before STREQUAL c_after OR NOT h_before STREQUAL h_after)
  message(FATAL_ERROR "Invalid depfile changed the existing output pair")
endif()
run("${DICE}" --query "${root}/system.dice")
assert_contains("${result_text}" "event EVENT_TEST 128")
assert_contains("${result_text}" "slot first 32 forced")
assert_contains("${result_text}" "produces first 15/200")
run("${DICE}" --graph "${root}/system.dice")
assert_contains("${result_text}" "style=dashed")
file(READ "${out}/dice.c" source)
if(source MATCHES "INTERPOSE\\(|struct self \\{|mempool_alloc\\(|ps_initd_\\(")
  message(FATAL_ERROR "Generated source contains a runtime or interceptor implementation")
endif()
string(REGEX REPLACE ".*DICE_HIDE enum ps_err\nps_dispatch_" "" dispatch "${source}")
assert_contains("${dispatch}" "case 128:")
if(dispatch MATCHES "case 200:")
  message(FATAL_ERROR "Unused event has a dispatch case")
endif()

set(flags -std=gnu11 -D_GNU_SOURCE -DDICE_ROLLED=1 -Wall -Wextra -Werror -fPIC
          "-I${out}" "-I${SOURCE}/include" "-I${SOURCE}/src/dice"
          "-I${SOURCE}/deps/libvsync/include")
file(READ "${out}/dice.h" generated_header)
assert_contains("${generated_header}" "#include <dice/pubsub.h>")
if(generated_header MATCHES "struct malloc_event \\{|MIT License")
  message(FATAL_ERROR "Generated header unexpectedly packs public headers")
endif()
include("${FIXTURES}/core.cmake")
set(link -pthread ${DL_LIBS})
if(APPLE)
  set(suffix .dylib)
  set(shared -dynamiclib)
  set(plugin_flags -undefined dynamic_lookup)
  set(preload DYLD_INSERT_LIBRARIES)
else()
  set(suffix .so)
  set(shared -shared)
  set(plugin_flags)
  set(preload LD_PRELOAD)
endif()
# A failed rename must leave the entire previous pair intact, including when
# replacing the source fails after the new header has already been installed.
set(replacement "${root}/replacement")
set(rename_hook "${root}/rename-fail${suffix}")
run("${CC}" ${flags} ${shared} "${FIXTURES}/rename-fail.c" ${link}
    -o "${rename_hook}")
string(REPLACE "(number 32)" "(number 33)" changed "${config}")
file(WRITE "${root}/changed.dice" "${changed}")
run("${DICE}" "${root}/system.dice" -o "${replacement}" --name foo)
file(SHA256 "${replacement}/foo.c" original_c)
file(SHA256 "${replacement}/foo.h" original_h)
foreach(extension h c)
  expect_failure("cannot replace output" "${CMAKE_COMMAND}" -E env
      "${preload}=${rename_hook}" "DICE_TEST_RENAME_FAIL=${replacement}/foo.${extension}"
      "${DICE}" "${root}/changed.dice" -o "${replacement}" --name foo)
  file(SHA256 "${replacement}/foo.c" restored_c)
  file(SHA256 "${replacement}/foo.h" restored_h)
  if(NOT original_c STREQUAL restored_c OR NOT original_h STREQUAL restored_h)
    message(FATAL_ERROR "Failed replacement changed the previous output pair")
  endif()
  file(GLOB leftovers "${replacement}/.*")
  if(leftovers)
    message(FATAL_ERROR "Failed replacement left temporary files: ${leftovers}")
  endif()
endforeach()
run("${DICE}" "${root}/changed.dice" -o "${replacement}" --name foo)
file(SHA256 "${replacement}/foo.c" changed_c)
file(SHA256 "${replacement}/foo.h" changed_h)
if(original_c STREQUAL changed_c OR original_h STREQUAL changed_h)
  message(FATAL_ERROR "Successful replacement did not update both outputs")
endif()
file(REMOVE "${replacement}/foo.c" "${replacement}/foo.h")
expect_failure("cannot replace output" "${CMAKE_COMMAND}" -E env
    "${preload}=${rename_hook}" "DICE_TEST_RENAME_FAIL=${replacement}/foo.c"
    "${DICE}" "${root}/system.dice" -o "${replacement}" --name foo)
file(GLOB leftovers "${replacement}/*" "${replacement}/.*")
if(leftovers)
  message(FATAL_ERROR "Failed initial generation left output files: ${leftovers}")
endif()

# Interceptors use the generated API, but their source is never in dice.c.
function(build_runtime library generated handlers)
  get_filename_component(directory "${generated}" DIRECTORY)
  get_filename_component(name "${generated}" NAME_WE)
  build_core(objects "${generated}" ${ARGN})
  foreach(module self pthread_create malloc)
    string(TOUPPER "${module}" slot)
    set(object "${directory}/${module}.o")
    run("${CC}" ${flags} ${ARGN} "-I${SOURCE}/include"
        "-I${SOURCE}/deps/libvsync/include" -include "${directory}/${name}.h"
        "-DDICE_MODULE_SLOT=SLOT_DICE_${slot}" -DDICE_DISPATCH_MODULE
        -c "${SOURCE}/src/mod/${module}.c" -o "${object}")
    list(APPEND objects "${object}")
  endforeach()
  run("${CC}" ${flags} ${ARGN} -DDICE_DISPATCH_MODULE ${shared} "${generated}" "${handlers}"
      ${objects} ${link} -o "${library}")
endfunction()

set(lib "${out}/runtime${suffix}")
set(mod "${out}/plugin${suffix}")
set(app "${out}/app")
build_runtime("${lib}" "${out}/dice.c" "${FIXTURES}/handlers.c")
run("${CC}" ${flags} ${shared} ${plugin_flags} "${FIXTURES}/plugin.c" -o "${mod}")
run("${CC}" ${flags} "${FIXTURES}/main.c" "${lib}" ${link} -o "${app}")
run("${app}")
assert_contains("${result_text}" "passed")
run("${CMAKE_COMMAND}" -E env "${preload}=${lib}:${mod}" WITH_PLUGIN=1 "${app}")
assert_contains("${result_text}" "allocation captured")
assert_contains("${result_text}" "thread captured")
assert_contains("${result_text}" "passed")

# Custom basenames preserve the API and work for linked handlers and plugins.
set(named "${root}/named")
run("${DICE}" "${root}/system.dice" --name lotto-runtime -o "${named}")
if(EXISTS "${named}/dice.c" OR EXISTS "${named}/dice.h")
  message(FATAL_ERROR "Custom basename unexpectedly produced default filenames")
endif()
file(SHA256 "${named}/lotto-runtime.h" named_header)
if(NOT named_header STREQUAL h_before)
  message(FATAL_ERROR "Custom basename changed the generated header API")
endif()
set(named_flags ${flags})
list(REMOVE_ITEM named_flags "-I${out}")
list(APPEND named_flags "-I${named}")
foreach(fixture handlers plugin main)
  file(READ "${FIXTURES}/${fixture}.c" text)
  string(REPLACE "\"dice.h\"" "\"lotto-runtime.h\"" text "${text}")
  file(WRITE "${named}/${fixture}.c" "${text}")
endforeach()
build_runtime("${named}/runtime${suffix}" "${named}/lotto-runtime.c" "${named}/handlers.c" "-I${named}")
run("${CC}" ${named_flags} ${shared} ${plugin_flags} "${named}/plugin.c"
    -o "${named}/plugin${suffix}")
run("${CC}" ${named_flags} "${named}/main.c" "${named}/runtime${suffix}"
    ${link} -o "${named}/app")
run("${CMAKE_COMMAND}" -E env WITH_PLUGIN=1
    "${preload}=${named}/runtime${suffix}:${named}/plugin${suffix}" "${named}/app")
assert_contains("${result_text}" "passed")
foreach(invalid "../escape" "bad/name" "bad\"name")
  expect_failure("output name" "${DICE}" "${root}/system.dice"
      -o "${named}/invalid" --name "${invalid}")
endforeach()
if(EXISTS "${named}/invalid")
  message(FATAL_ERROR "Invalid basename created an output directory")
endif()
expect_failure("Usage:" "${DICE}" "${root}/system.dice" -o "${named}" --name)
expect_failure("Usage:" "${DICE}" "${root}/system.dice" -o "${named}"
    --name first --name second)

# Plugins built against a different generated header fail before registration.
file(READ "${out}/dice.h" header)
string(REPLACE "roll-1-" "wrong--" bad_header "${header}")
file(WRITE "${out}/dice.h" "${bad_header}")
run("${CC}" ${flags} ${shared} ${plugin_flags} "${FIXTURES}/plugin.c" -o "${mod}")
expect_failure("different generated dice.h" "${CMAKE_COMMAND}" -E env
               "${preload}=${lib}:${mod}" WITH_PLUGIN=1 "${app}")
file(WRITE "${out}/dice.h" "${header}")
# Declarations must match the source: undeclared consumption is a compile error.
file(WRITE "${out}/undeclared.c" "#define DICE_MODULE_SLOT SLOT_FIRST\n#include \"dice.h\"\nPS_SUBSCRIBE(CHAIN_EMPTY, EVENT_TEST, {})\n")
expect_failure("dice_consumes" "${CC}" ${flags} -c "${out}/undeclared.c" -o "${out}/undeclared.o")

string(REPLACE "(plugins true)" "(plugins false)" sealed "${config}")
file(WRITE "${root}/sealed.dice" "${sealed}")
run("${DICE}" "${root}/sealed.dice" -o "${out}")
build_runtime("${lib}" "${out}/dice.c" "${FIXTURES}/handlers.c")
run("${CC}" ${flags} "${FIXTURES}/main.c" "${lib}" ${link} -o "${app}")
run("${app}")
assert_contains("${result_text}" "passed")
run("${CC}" ${flags} ${shared} ${plugin_flags} "${FIXTURES}/plugin.c" -o "${mod}")
expect_failure("could not subscribe plugin" "${CMAKE_COMMAND}" -E env
               "${preload}=${lib}:${mod}" WITH_PLUGIN=1 "${app}")

file(SHA256 "${out}/dice.c" saved_c)
file(SHA256 "${out}/dice.h" saved_h)
function(bad_config text expected)
  file(WRITE "${root}/bad.dice" "${text}")
  expect_failure("${expected}" "${DICE}" "${root}/bad.dice" -o "${out}")
  file(SHA256 "${out}/dice.c" now_c)
  file(SHA256 "${out}/dice.h" now_h)
  if(NOT now_c STREQUAL saved_c OR NOT now_h STREQUAL saved_h)
    message(FATAL_ERROR "Invalid input replaced generated output")
  endif()
endfunction()
bad_config("(dice (schema 1) (slot a (before b)) (slot b (before c)) (slot c (before a)))" "a -> b -> c -> a")
bad_config("(dice (schema 1) (slot a (number 10) (before b)) (slot b (number 5)))" "forced number")
bad_config("(dice (schema 1) (slot a (number 10) (before b)) (slot b (before c)) (slot c (number 11)))" "forced number|cannot fit")
bad_config("(dice (schema 1) (slot a (number 2)) (slot b (number 2)))" "both force number")
bad_config("(dice (schema 1) (slot a (before missing)))" "unknown slot")
bad_config("(dice (schema 1) (events (EVENT_A 128) (EVENT_B 128)))" "ID collision")
bad_config("(dice (schema 1) (events (EVENT_A 1)))" "ID collision")
bad_config("(dice (schema 1) (events (ANY_EVENT 128)))" "duplicate or reserved identifier")
bad_config("(dice (schema 1) (chains (CHAIN_DICE_CONTROL 7)))" "duplicate or reserved identifier")
bad_config("(dice (schema 1) (events (EVENT_A 0)))" "expected integer")
bad_config("(dice (schema 1) (chains (CHAIN_A 0)))" "expected integer")
bad_config("(dice (schema 1) (runtime (embed self)))" "unknown runtime field embed")
bad_config("(dice (schema 1) (embed self))" "unknown form embed")
bad_config("(dice (schema 1) (slot dice-core))" "reserved slot dice-core")
bad_config("(dice (schema 1) (slot dice_core))" "reserved slot dice-core")
bad_config("(dice (schema 1) (include \"bad.dice\"))" "include cycle")
bad_config("(dice (schema 1) (runtime (plugins yes)))" "true or false")
bad_config("(dice (schema 1) (slot monitor (plugin true)))" "unknown slot field plugin")
bad_config("(dice (schema 1) (slot monitor (callback true)))" "unknown slot field callback")
bad_config("(dice)" "expected .schema 1.")
bad_config("(dice (version 1))" "unknown form version")
bad_config("(dice (schema 2))" "expected integer")
bad_config("(dice (schema 1) (schema 1))" "duplicate schema")
bad_config("(dice (schema 1) (events (EVENT_A 65535)))" "expected integer")
bad_config("(dice (schema 1) (slot a (consumes (CHAIN_A EVENT_X EVENT_X))))" "duplicate consumption")
bad_config("(dice (schema 1) (slot a (produces (CHAIN_A EVENT_X EVENT_X))))" "duplicate production")
bad_config("(dice (schema 1) (slot A) (slot a))" "collide")
bad_config("(dice (schema 1) (slot first-stage) (slot first_stage))" "duplicate slot")
bad_config("(dice (schema 1) (events EVENT-TEST EVENT_TEST))" "duplicate or reserved identifier")
bad_config("(dice (schema 1) (chains CHAIN-TEST CHAIN_TEST))" "duplicate or reserved identifier")
bad_config("(dice (schema 1) (events (ANY-EVENT 128)))" "duplicate or reserved identifier")
bad_config("(dice (schema 1) (runtime (mempool-size 4096) (mempool_size 8192)))" "duplicate runtime field")
bad_config("(dice (schema 1) (slot a (before b-c)) (slot b_c (before a)))" "cycle")
bad_config("(dice (schema 1) (slot a (consumes (CHAIN-A EVENT-X EVENT_X))))" "duplicate consumption")
bad_config("(dice (schema 1) (eval anything))" "unknown form")
bad_config("(dice (schema 1)" "unclosed list")
bad_config("(dice (schema 1)) (dice)" "end of file")
bad_config("(dice (schema 1) (include \"bad\\q\"))" "unsupported string escape")

# Both spellings resolve identically, including across includes and constraints.
# The hyphenated include path must remain unchanged.
file(WRITE "${root}/aliases-events.dice"
     "(dice (events (EVENT_DATA 200)) (chains (CHAIN_FLOW 15)))")
set(aliases [=[(dice (schema 1)
  (include "aliases-events.dice")
  (runtime (mempool_size 209715200))
  (slot dice_self (before first-stage))
  (slot first_stage (after dice-self) (before last-stage)
    (consumes (CHAIN-FLOW EVENT-DATA ANY-EVENT)
              (CHAIN-DICE-CONTROL EVENT-DICE-INIT))
    (produces (CHAIN_FLOW EVENT_DATA)))
  (slot last_stage (after first-stage)
    (consumes (CHAIN_FLOW EVENT_DATA))))
]=])
file(WRITE "${root}/aliases.dice" "${aliases}")
run("${DICE}" "${root}/aliases.dice" -o "${root}/aliases")
file(SHA256 "${root}/aliases/dice.c" alias_c)
file(SHA256 "${root}/aliases/dice.h" alias_h)
run("${DICE}" --query "${root}/aliases.dice")
set(alias_query "${result_text}")
foreach(separator "-" "_")
  string(REPLACE "_" "${separator}" spelling "${aliases}")
  # Only symbols change; preserve the include filename verbatim.
  if(separator STREQUAL "_")
    string(REPLACE "-" "_" spelling "${spelling}")
    string(REPLACE "aliases_events.dice" "aliases-events.dice" spelling "${spelling}")
  endif()
  file(WRITE "${root}/aliases.dice" "${spelling}")
  run("${DICE}" "${root}/aliases.dice" -o "${root}/aliases")
  file(SHA256 "${root}/aliases/dice.c" spelled_c)
  file(SHA256 "${root}/aliases/dice.h" spelled_h)
  run("${DICE}" --query "${root}/aliases.dice")
  if(NOT alias_c STREQUAL spelled_c OR NOT alias_h STREQUAL spelled_h
     OR NOT alias_query STREQUAL result_text)
    message(FATAL_ERROR "Hyphen and underscore spellings produced different configurations")
  endif()
endforeach()

# Produces-only endpoints are inferred; unused standard-range IDs can be pinned.
file(WRITE "${root}/inferred.dice" "(dice (schema 1) (events (EVENT_OLD 110)) (slot source (produces (CHAIN_NEW EVENT_NEW))))")
run("${DICE}" --query "${root}/inferred.dice")
assert_contains("${result_text}" "event EVENT_NEW 128")
assert_contains("${result_text}" "event EVENT_OLD 110")
assert_contains("${result_text}" "chain CHAIN_NEW 7")
# A deadline-aware order must place b before unrelated a to meet c's forced ID.
file(WRITE "${root}/forced.dice" "(dice (schema 1) (slot a) (slot b (before c)) (slot c (number 2)))")
run("${DICE}" --query "${root}/forced.dice")
assert_contains("${result_text}" "slot b 1")
assert_contains("${result_text}" "slot c 2 forced")
assert_contains("${result_text}" "slot a 3")
# Large gaps do not require iterating over every integer slot.
file(WRITE "${root}/large.dice" "(dice (schema 1) (slot a (number 2147483646) (before b)) (slot b))")
run("${DICE}" --query "${root}/large.dice")
assert_contains("${result_text}" "slot b 2147483647")

file(WRITE "${root}/empty.dice" "(dice (schema 1))")
run("${DICE}" --query "${root}/empty.dice")
assert_contains("${result_text}" "event ANY_EVENT 0\n")
assert_contains("${result_text}" "chain CHAIN_DICE_CONTROL 0\n")
run("${DICE}" "${root}/empty.dice" -o "${out}")
file(READ "${out}/dice.h" empty_header)
assert_contains("${empty_header}" "#define ANY_EVENT 0\n")
assert_contains("${empty_header}" "#define CHAIN_DICE_CONTROL 0\n")
run("${CC}" ${flags} -c "${out}/dice.c" -o "${out}/empty.o")
run("${CC}" ${flags} -DDICE_CHECK_ROUTES=1 -c "${out}/dice.c" -o "${out}/empty-checked.o")

# Checked builds enforce dynamic routes, including forwarding by separately
# compiled modules and plugins.
run("${DICE}" "${FIXTURES}/routes.dice" -o "${out}")
set(checked ${flags} -DDICE_CHECK_ROUTES=1)
build_runtime("${lib}" "${out}/dice.c" "${FIXTURES}/routes-handlers.c" -DDICE_CHECK_ROUTES=1)
run("${CC}" ${checked} ${shared} ${plugin_flags} "${FIXTURES}/routes-plugin.c" -o "${mod}")
run("${CC}" ${checked} "${FIXTURES}/routes-main.c" "${lib}" ${link} -o "${app}")
run("${app}")
assert_contains("${result_text}" "route checks passed")
run("${CMAKE_COMMAND}" -E env "${preload}=${lib}:${mod}" WITH_PLUGIN=1 "${app}")
assert_contains("${result_text}" "route checks passed")
foreach(mode produces event pointer)
  expect_failure("undeclared produces" "${app}" "${mode}")
endforeach()
foreach(mode consumes any slot)
  expect_failure("undeclared consumes" "${app}" "${mode}")
endforeach()
file(WRITE "${out}/bad-plugin.c" "#define DICE_MODULE_SLOT SLOT_OBSERVER\n#include \"dice.h\"\nPS_SUBSCRIBE(CHAIN_TEST, EVENT_TEST, {})\n")
expect_failure("undeclared slot consumption" "${CC}" ${checked} -c "${out}/bad-plugin.c" -o "${out}/bad-plugin.o")
# Missing slot context must not silently exempt application publications.
file(WRITE "${out}/anonymous.c" "#include \"dice.h\"\nint main(void) { return ps_publish(CHAIN_TEST, EVENT_TEST, 0, 0); }\n")
run("${CC}" ${checked} "${out}/anonymous.c" "${lib}" ${link} -o "${out}/anonymous")
expect_failure("undeclared produces" "${out}/anonymous")
# A release-built plugin cannot bypass the checked runtime via missing macros.
# DICE_PLUGIN_MODULE also takes precedence over a dispatch build flag.
run("${CC}" ${flags} -DDICE_DISPATCH_MODULE ${shared} ${plugin_flags}
    "${FIXTURES}/routes-plugin.c" -o "${mod}")
expect_failure("different generated dice.h" "${CMAKE_COMMAND}" -E env
               "${preload}=${lib}:${mod}" WITH_PLUGIN=1 "${app}")

# Release builds omit route validation entirely and retain dynamic APIs.
build_runtime("${lib}" "${out}/dice.c" "${FIXTURES}/routes-handlers.c")
run("${CC}" ${flags} "${FIXTURES}/routes-main.c" "${lib}" ${link} -o "${app}")
run("${app}")
run("${CMAKE_COMMAND}" -E env "${preload}=${lib}:${mod}" WITH_PLUGIN=1 "${app}")
foreach(mode produces event consumes any slot pointer)
  run("${app}" "${mode}")
endforeach()
# Reused pubsub core: initialization/reentrancy, sorted indexed callbacks and
# wildcard expansion with both dense IDs and sparse forced IDs near UINT16_MAX.
foreach(high_id 129 65534)
  foreach(plugins true false)
    file(WRITE "${root}/pubsub.dice" "(dice (schema 1)
      (runtime (plugins ${plugins}))
      (events (EVENT_LOW 128) (EVENT_HIGH ${high_id}))
      (chains (CHAIN_LOW 7) (CHAIN_HIGH ${high_id}))
      (slot initializer
        (consumes (CHAIN_DICE_CONTROL EVENT_DICE_INIT EVENT_DICE_READY)
                  (CHAIN_LOW EVENT_LOW))
        (produces (CHAIN_LOW EVENT_LOW))))")
    run("${DICE}" "${root}/pubsub.dice" -o "${out}")
    build_core(objects "${out}/dice.c")
    run("${CC}" ${flags} "${out}/dice.c" "${FIXTURES}/pubsub.c"
        ${objects} ${link} -o "${app}")
    run("${app}")
    assert_contains("${result_text}" "pubsub passed")
  endforeach()
endforeach()
# The same module source works with ordinary Dice includes and guarded IDs.
# Force-inclusion selects the generated API before any legacy header is read.
file(WRITE "${root}/compat.dice" "(dice (schema 1)
  (slot receiver (consumes (CHAIN_COMPAT EVENT_COMPAT)
                           (CHAIN_DICE_CONTROL EVENT_DICE_INIT))))")
run("${DICE}" "${root}/compat.dice" -o "${out}")
set(compat_flags ${flags} "-I${SOURCE}/include"
    -include "${out}/dice.h" -DDICE_MODULE_SLOT=SLOT_RECEIVER)
run("${CC}" ${flags} -c "${out}/dice.c" -o "${out}/runtime.o")
build_core(objects "${out}/dice.c")
run("${CC}" ${compat_flags} ${shared} "${out}/runtime.o" ${objects}
    "${FIXTURES}/compat/subscriber.c" ${link} -o "${lib}")
run("${CC}" ${compat_flags} "${FIXTURES}/compat/main.c" "${lib}" ${link} -o "${app}")
run("${app}")
# Defining generated mode alone must not silently restore any legacy numbers.
file(GLOB headers "${SOURCE}/include/dice/events/*.h" "${SOURCE}/include/dice/chains/*.h")
file(WRITE "${out}/ids.c" "#include <dice/types.h>\n")
foreach(header IN LISTS headers)
  file(APPEND "${out}/ids.c" "#include \"${header}\"\n")
endforeach()
run("${CC}" -D_GNU_SOURCE -DDICE_ROLLED=1 -E -dM
    "-I${SOURCE}/include" "-I${SOURCE}/deps/libvsync/include" "${out}/ids.c")
if(result_text MATCHES "#define (EVENT_[A-Z_]+|CHAIN_DICE_CONTROL|ANY_EVENT|CAPTURE_[A-Z_]+|INTERCEPT_(EVENT|BEFORE|AFTER)) ")
  message(FATAL_ERROR "Legacy IDs leaked into generated mode")
endif()
# Compact event indexing must work with separately compiled modules and plugins.
file(WRITE "${root}/events.dice" "(dice (events (EVENT_UNUSED 60000)) (chains (CHAIN_EMPTY 60000)))\n")
run("${DICE}" "${root}/system.dice" -o "${out}")
build_runtime("${lib}" "${out}/dice.c" "${FIXTURES}/handlers.c")
run("${CC}" ${flags} ${shared} ${plugin_flags} "${FIXTURES}/plugin.c" -o "${mod}")
run("${CC}" ${flags} "${FIXTURES}/main.c" "${lib}" ${link} -o "${app}")
run("${app}")
run("${CMAKE_COMMAND}" -E env "${preload}=${lib}:${mod}" WITH_PLUGIN=1 "${app}")
# Sparse identifiers must also work in a sealed runtime.
string(REPLACE "(plugins true)" "(plugins false)" sealed_config "${config}")
file(WRITE "${root}/sealed-sparse.dice" "${sealed_config}")
run("${DICE}" "${root}/sealed-sparse.dice" -o "${out}")
build_runtime("${lib}" "${out}/dice.c" "${FIXTURES}/handlers.c")
run("${CC}" ${flags} "${FIXTURES}/main.c" "${lib}" ${link} -o "${app}")
run("${app}")
# Slot boundaries at INT_MAX must not wrap the default plugin slot negative.
file(WRITE "${root}/maximum.dice" "(dice (schema 1) (slot last (number 2147483647)))")
run("${DICE}" "${root}/maximum.dice" -o "${out}")
file(WRITE "${out}/maximum.c" "#include \"dice.h\"\n#include <assert.h>\n
static enum ps_err cb(chain_id c, type_id t, void *e, struct metadata *m) {
  (void)c; (void)t; (void)e; (void)m; return PS_OK;
}
int main(void) {
  _Static_assert(DICE_LAST_KNOWN_SLOT == 2147483647, \"maximum slot\");
  assert(ps_subscribe(CHAIN_DICE_CONTROL, EVENT_DICE_NOP, cb, 2147483647) == PS_INVALID);
  assert(ps_subscribe(CHAIN_DICE_CONTROL, EVENT_DICE_NOP, cb, DICE_DEFAULT_PLUGIN_SLOT) == PS_INVALID);
}\n")
build_core(objects "${out}/dice.c")
run("${CC}" ${flags} "${out}/dice.c" "${out}/maximum.c"
    ${objects} ${link} -o "${app}")
run("${app}")
message(STATUS "roll: inferred IDs, ordering, sparse dispatch, plugins and route enforcement passed")
