# Build and run using only the generated pair and application source fixtures.
function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE result OUTPUT_VARIABLE stdout
                  ERROR_VARIABLE stderr TIMEOUT 30)
  if(NOT result STREQUAL "0")
    message(FATAL_ERROR "${ARGV}: ${result}\n${stdout}${stderr}")
  endif()
  set(result_text "${stdout}${stderr}" PARENT_SCOPE)
endfunction()
function(expect_failure expected)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE stdout
                  ERROR_VARIABLE stderr TIMEOUT 30)
  if(result STREQUAL "0" OR NOT "${stdout}${stderr}" MATCHES "${expected}")
    message(FATAL_ERROR "Expected failure '${expected}': ${ARGN}\n${result}\n${stdout}${stderr}")
  endif()
endfunction()
function(assert_contains text pattern)
  if(NOT "${text}" MATCHES "${pattern}")
    message(FATAL_ERROR "Missing '${pattern}' in: ${text}")
  endif()
endfunction()

set(root "${WORK}/integration")
set(out "${root}/generated")
file(MAKE_DIRECTORY "${root}")
set(config [=[(dice (version 1)
  (include "events.dice")
  (runtime (embed self pthread_create malloc) (plugins true))
  (slot first (number 32) (before later)
    (consumes (CHAIN_TEST EVENT_TEST ANY_EVENT))
    (produces (CHAIN_EMPTY EVENT_UNUSED)))
  (slot later (number 40) (after first)
    (consumes (CHAIN_TEST ANY_EVENT))))
]=])
file(WRITE "${root}/system.dice" "${config}")
# EVENT_TEST and CHAIN_TEST are inferred from slots; explicit IDs are optional.
file(WRITE "${root}/events.dice" "(dice (events (EVENT_UNUSED 200)) (chains (CHAIN_EMPTY 15)))\n")
run("${DICE}" roll "${root}/system.dice" --output "${out}")
file(SHA256 "${out}/dice.c" c_before)
file(SHA256 "${out}/dice.h" h_before)
run("${DICE}" roll "${root}/system.dice" --output "${out}")
file(SHA256 "${out}/dice.c" c_after)
file(SHA256 "${out}/dice.h" h_after)
if(NOT c_before STREQUAL c_after OR NOT h_before STREQUAL h_after)
  message(FATAL_ERROR "Non-deterministic generation")
endif()
run("${DICE}" query "${root}/system.dice")
assert_contains("${result_text}" "event EVENT_TEST 128")
assert_contains("${result_text}" "slot first 32 forced")
assert_contains("${result_text}" "produces first 15/200")
run("${DICE}" graph "${root}/system.dice")
assert_contains("${result_text}" "style=dashed")
file(READ "${out}/dice.c" source)
string(REGEX REPLACE ".*DICE_HIDE enum ps_err\nps_dispatch_" "" dispatch "${source}")
assert_contains("${dispatch}" "case 128:")
if(dispatch MATCHES "case 200:")
  message(FATAL_ERROR "Unused event has a dispatch case")
endif()

set(flags -std=gnu11 -D_GNU_SOURCE -Wall -Wextra -Werror -fPIC "-I${out}")
set(link -pthread)
if(APPLE)
  set(suffix .dylib)
  set(shared -dynamiclib)
  set(plugin_flags -undefined dynamic_lookup)
  set(preload DYLD_INSERT_LIBRARIES)
else()
  set(suffix .so)
  set(shared -shared)
  set(plugin_flags)
  set(preload LD_PRELOAD)
  list(APPEND link -ldl)
endif()
set(lib "${out}/runtime${suffix}")
set(mod "${out}/plugin${suffix}")
set(app "${out}/app")
run("${CC}" ${flags} ${shared} "${out}/dice.c" "${FIXTURES}/handlers.c" ${link} -o "${lib}")
run("${CC}" ${flags} ${shared} ${plugin_flags} "${FIXTURES}/plugin.c" -o "${mod}")
run("${CC}" ${flags} "${FIXTURES}/main.c" "${lib}" ${link} -o "${app}")
run("${app}")
assert_contains("${result_text}" "passed")
run("${CMAKE_COMMAND}" -E env "${preload}=${lib}:${mod}" WITH_PLUGIN=1 "${app}")
assert_contains("${result_text}" "allocation captured")
assert_contains("${result_text}" "thread captured")
assert_contains("${result_text}" "passed")

# Plugins built against a different generated header fail before registration.
file(READ "${out}/dice.h" header)
string(REPLACE "roll-1-" "wrong--" bad_header "${header}")
file(WRITE "${out}/dice.h" "${bad_header}")
run("${CC}" ${flags} ${shared} ${plugin_flags} "${FIXTURES}/plugin.c" -o "${mod}")
expect_failure("different generated dice.h" "${CMAKE_COMMAND}" -E env
               "${preload}=${lib}:${mod}" WITH_PLUGIN=1 "${app}")
file(WRITE "${out}/dice.h" "${header}")
# Declarations must match the source: undeclared consumption is a compile error.
file(WRITE "${out}/undeclared.c" "#define DICE_MODULE_SLOT DICE_SLOT_FIRST\n#include \"dice.h\"\nPS_SUBSCRIBE(CHAIN_EMPTY, EVENT_TEST, {})\n")
expect_failure("dice_consumes" "${CC}" ${flags} -c "${out}/undeclared.c" -o "${out}/undeclared.o")

string(REPLACE "(plugins true)" "(plugins false)" sealed "${config}")
file(WRITE "${root}/sealed.dice" "${sealed}")
run("${DICE}" roll "${root}/sealed.dice" -o "${out}")
run("${CC}" ${flags} ${shared} "${out}/dice.c" "${FIXTURES}/handlers.c" ${link} -o "${lib}")
run("${CC}" ${flags} "${FIXTURES}/main.c" "${lib}" ${link} -o "${app}")
run("${app}")
assert_contains("${result_text}" "passed")
run("${CC}" ${flags} ${shared} ${plugin_flags} "${FIXTURES}/plugin.c" -o "${mod}")
expect_failure("could not subscribe plugin" "${CMAKE_COMMAND}" -E env
               "${preload}=${lib}:${mod}" WITH_PLUGIN=1 "${app}")

file(SHA256 "${out}/dice.c" saved_c)
file(SHA256 "${out}/dice.h" saved_h)
function(bad_config text expected)
  file(WRITE "${root}/bad.dice" "${text}")
  expect_failure("${expected}" "${DICE}" roll "${root}/bad.dice" -o "${out}")
  file(SHA256 "${out}/dice.c" now_c)
  file(SHA256 "${out}/dice.h" now_h)
  if(NOT now_c STREQUAL saved_c OR NOT now_h STREQUAL saved_h)
    message(FATAL_ERROR "Invalid input replaced generated output")
  endif()
endfunction()
bad_config("(dice (version 1) (slot a (before b)) (slot b (before c)) (slot c (before a)))" "a -> b -> c -> a")
bad_config("(dice (version 1) (slot a (number 10) (before b)) (slot b (number 5)))" "forced number")
bad_config("(dice (version 1) (slot a (number 10) (before b)) (slot b (before c)) (slot c (number 11)))" "forced number|cannot fit")
bad_config("(dice (version 1) (slot a (number 2)) (slot b (number 2)))" "both force number")
bad_config("(dice (version 1) (slot a (before missing)))" "unknown slot")
bad_config("(dice (version 1) (events (EVENT_A 128) (EVENT_B 128)))" "ID collision")
bad_config("(dice (version 1) (events (EVENT_A 1)))" "ID collision")
bad_config("(dice (version 1) (runtime (embed missing)))" "unknown embedded module")
bad_config("(dice (version 1) (include \"bad.dice\"))" "include cycle")
bad_config("(dice (version 1) (runtime (plugins yes)))" "true or false")
bad_config("(dice (version 1) (slot monitor (plugin yes)))" "true or false")
bad_config("(dice (version 1) (slot monitor (callback true) (plugin true)))" "duplicate slot field")
bad_config("(dice (version 1) (events (EVENT_A 65535)))" "expected integer")
bad_config("(dice (version 1) (slot a (consumes (CHAIN_A EVENT_X EVENT_X))))" "duplicate consumption")
bad_config("(dice (version 1) (slot a (produces (CHAIN_A EVENT_X EVENT_X))))" "duplicate production")
bad_config("(dice (version 1) (slot A) (slot a))" "collide")
bad_config("(dice (version 1) (eval anything))" "unknown form")
bad_config("(dice (version 1)" "unclosed list")
bad_config("(dice (version 1)) (dice)" "end of file")
bad_config("(dice (version 1) (include \"bad\\q\"))" "unsupported string escape")

# Produces-only endpoints are inferred; unused standard-range IDs can be pinned.
file(WRITE "${root}/inferred.dice" "(dice (version 1) (events (EVENT_OLD 110)) (slot source (produces (CHAIN_NEW EVENT_NEW))))")
run("${DICE}" query "${root}/inferred.dice")
assert_contains("${result_text}" "event EVENT_NEW 128")
assert_contains("${result_text}" "event EVENT_OLD 110")
assert_contains("${result_text}" "chain CHAIN_NEW 7")
# A deadline-aware order must place b before unrelated a to meet c's forced ID.
file(WRITE "${root}/forced.dice" "(dice (version 1) (slot a) (slot b (before c)) (slot c (number 2)))")
run("${DICE}" query "${root}/forced.dice")
assert_contains("${result_text}" "slot b 1")
assert_contains("${result_text}" "slot c 2 forced")
assert_contains("${result_text}" "slot a 3")
# Large gaps do not require iterating over every integer slot.
file(WRITE "${root}/large.dice" "(dice (version 1) (slot a (number 2147483646) (before b)) (slot b))")
run("${DICE}" query "${root}/large.dice")
assert_contains("${result_text}" "slot b 2147483647")

run("${DICE}" modules)
string(REPLACE "\n" " " modules "${result_text}")
if(APPLE)
  string(REPLACE "pthread_spinlock" "" modules "${modules}")
endif()
file(WRITE "${root}/broad.dice" "(dice (version 1) (runtime (embed ${modules})))")
run("${DICE}" roll "${root}/broad.dice" -o "${out}")
run("${CC}" ${flags} -c "${out}/dice.c" -o "${out}/broad.o")
run("${CC}" ${flags} -DDICE_CHECK_ROUTES=1 -c "${out}/dice.c" -o "${out}/broad-checked.o")
file(WRITE "${root}/empty.dice" "(dice (version 1))")
run("${DICE}" roll "${root}/empty.dice" -o "${out}")
run("${CC}" ${flags} -c "${out}/dice.c" -o "${out}/empty.o")
run("${CC}" ${flags} -DDICE_CHECK_ROUTES=1 -c "${out}/dice.c" -o "${out}/empty-checked.o")

# Checked builds enforce dynamic routes, including builtin forwarding and plugins.
run("${DICE}" roll "${FIXTURES}/routes.dice" -o "${out}")
set(checked ${flags} -DDICE_CHECK_ROUTES=1)
run("${CC}" ${checked} ${shared} "${out}/dice.c" "${FIXTURES}/routes-handlers.c" ${link} -o "${lib}")
run("${CC}" ${checked} ${shared} ${plugin_flags} "${FIXTURES}/routes-plugin.c" -o "${mod}")
run("${CC}" ${checked} "${FIXTURES}/routes-main.c" "${lib}" ${link} -o "${app}")
run("${app}")
assert_contains("${result_text}" "route checks passed")
run("${CMAKE_COMMAND}" -E env "${preload}=${lib}:${mod}" WITH_PLUGIN=1 "${app}")
assert_contains("${result_text}" "route checks passed")
foreach(mode produces event pointer)
  expect_failure("undeclared produces" "${app}" "${mode}")
endforeach()
foreach(mode consumes any slot)
  expect_failure("undeclared consumes" "${app}" "${mode}")
endforeach()
file(WRITE "${out}/bad-plugin.c" "#define DICE_MODULE_SLOT DICE_SLOT_OBSERVER\n#include \"dice.h\"\nPS_SUBSCRIBE(CHAIN_TEST, EVENT_TEST, {})\n")
expect_failure("undeclared slot consumption" "${CC}" ${checked} -c "${out}/bad-plugin.c" -o "${out}/bad-plugin.o")
# Missing slot context must not silently exempt application publications.
file(WRITE "${out}/anonymous.c" "#include \"dice.h\"\nint main(void) { return ps_publish(CHAIN_TEST, EVENT_TEST, 0, 0); }\n")
run("${CC}" ${checked} "${out}/anonymous.c" "${lib}" ${link} -o "${out}/anonymous")
expect_failure("undeclared produces" "${out}/anonymous")
# A release-built plugin cannot bypass the checked runtime via missing macros.
run("${CC}" ${flags} ${shared} ${plugin_flags} "${FIXTURES}/routes-plugin.c" -o "${mod}")
expect_failure("different generated dice.h" "${CMAKE_COMMAND}" -E env
               "${preload}=${lib}:${mod}" WITH_PLUGIN=1 "${app}")

# Release builds omit route validation entirely and retain dynamic APIs.
run("${CC}" ${flags} ${shared} "${out}/dice.c" "${FIXTURES}/routes-handlers.c" ${link} -o "${lib}")
run("${CC}" ${flags} "${FIXTURES}/routes-main.c" "${lib}" ${link} -o "${app}")
run("${app}")
run("${CMAKE_COMMAND}" -E env "${preload}=${lib}:${mod}" WITH_PLUGIN=1 "${app}")
foreach(mode produces event consumes any slot pointer)
  run("${app}" "${mode}")
endforeach()
# Reused pubsub core: initialization/reentrancy, sorted indexed callbacks and
# wildcard expansion with both dense IDs and sparse forced IDs near UINT16_MAX.
foreach(high_id 129 65534)
  foreach(plugins true false)
    file(WRITE "${root}/pubsub.dice" "(dice (version 1)
      (runtime (plugins ${plugins}))
      (events (EVENT_LOW 128) (EVENT_HIGH ${high_id}))
      (chains (CHAIN_LOW 7) (CHAIN_HIGH ${high_id}))
      (slot initializer
        (consumes (CHAIN_CONTROL EVENT_DICE_INIT EVENT_DICE_READY)
                  (CHAIN_LOW EVENT_LOW))
        (produces (CHAIN_LOW EVENT_LOW))))")
    run("${DICE}" roll "${root}/pubsub.dice" -o "${out}")
    run("${CC}" ${flags} "${out}/dice.c" "${FIXTURES}/pubsub.c" ${link} -o "${app}")
    run("${app}")
    assert_contains("${result_text}" "pubsub passed")
  endforeach()
endforeach()
# The same module source works with ordinary Dice includes and guarded IDs.
# Force-inclusion selects the generated API before any legacy header is read.
file(WRITE "${root}/compat.dice" "(dice (version 1)
  (slot receiver (consumes (CHAIN_COMPAT EVENT_COMPAT)
                           (CHAIN_CONTROL EVENT_DICE_INIT))))")
run("${DICE}" roll "${root}/compat.dice" -o "${out}")
set(compat_flags ${flags} "-I${SOURCE}/include"
    -include "${out}/dice.h" -DDICE_MODULE_SLOT=DICE_SLOT_RECEIVER)
run("${CC}" ${flags} -c "${out}/dice.c" -o "${out}/runtime.o")
run("${CC}" ${compat_flags} ${shared} "${out}/runtime.o"
    "${FIXTURES}/compat/subscriber.c" ${link} -o "${lib}")
run("${CC}" ${compat_flags} "${FIXTURES}/compat/main.c" "${lib}" ${link} -o "${app}")
run("${app}")
# Defining generated mode alone must not silently restore any legacy numbers.
file(GLOB headers "${SOURCE}/include/dice/events/*.h" "${SOURCE}/include/dice/chains/*.h")
file(WRITE "${out}/ids.c" "#include <dice/types.h>\n")
foreach(header IN LISTS headers)
  file(APPEND "${out}/ids.c" "#include \"${header}\"\n")
endforeach()
run("${CC}" -D_GNU_SOURCE -DDICE_GENERATED_IDS=1 -E -dM
    "-I${SOURCE}/include" "-I${SOURCE}/deps/libvsync/include" "${out}/ids.c")
if(result_text MATCHES "#define (EVENT_[A-Z_]+|CHAIN_CONTROL|ANY_EVENT|CAPTURE_[A-Z_]+|INTERCEPT_(EVENT|BEFORE|AFTER)) ")
  message(FATAL_ERROR "Legacy IDs leaked into generated mode")
endif()
# Embedded modules can explicitly select callback delivery as well. Their
# hooks must be bound before the core publishes INIT, without early allocation.
string(REPLACE "(slot first" "(slot dice_self (callback true))
  (slot dice_pthread_create (callback true))
  (slot dice_malloc (callback true))
  (slot first" callback_config "${config}")
file(WRITE "${root}/builtin-callbacks.dice" "${callback_config}")
run("${DICE}" roll "${root}/builtin-callbacks.dice" -o "${out}")
run("${CC}" ${flags} ${shared} "${out}/dice.c" "${FIXTURES}/handlers.c" ${link} -o "${lib}")
run("${CC}" ${flags} ${shared} ${plugin_flags} "${FIXTURES}/plugin.c" -o "${mod}")
run("${CC}" ${flags} "${FIXTURES}/main.c" "${lib}" ${link} -o "${app}")
run("${app}")
run("${CMAKE_COMMAND}" -E env "${preload}=${lib}:${mod}" WITH_PLUGIN=1 "${app}")
# Compact event indexing must also initialize embedded callback heads correctly,
# including when the trailing plugin phase is disabled.
string(REPLACE "(plugins true)" "(plugins false)" callback_config "${callback_config}")
file(WRITE "${root}/builtin-callbacks.dice" "${callback_config}")
file(WRITE "${root}/events.dice" "(dice (events (EVENT_UNUSED 60000)) (chains (CHAIN_EMPTY 60000)))\n")
run("${DICE}" roll "${root}/builtin-callbacks.dice" -o "${out}")
run("${CC}" ${flags} ${shared} "${out}/dice.c" "${FIXTURES}/handlers.c" ${link} -o "${lib}")
run("${CC}" ${flags} "${FIXTURES}/main.c" "${lib}" ${link} -o "${app}")
run("${app}")
# Slot boundaries at INT_MAX must not wrap the default plugin slot negative.
file(WRITE "${root}/maximum.dice" "(dice (version 1) (slot last (number 2147483647)))")
run("${DICE}" roll "${root}/maximum.dice" -o "${out}")
file(WRITE "${out}/maximum.c" "#include \"dice.h\"\n#include <assert.h>\n
static enum ps_err cb(chain_id c, type_id t, void *e, struct metadata *m) {
  (void)c; (void)t; (void)e; (void)m; return PS_OK;
}
int main(void) {
  _Static_assert(DICE_LAST_KNOWN_SLOT == 2147483647, \"maximum slot\");
  assert(ps_subscribe(CHAIN_CONTROL, EVENT_DICE_NOP, cb, 2147483647) == PS_INVALID);
  assert(ps_subscribe(CHAIN_CONTROL, EVENT_DICE_NOP, cb, DICE_DEFAULT_PLUGIN_SLOT) == PS_INVALID);
}\n")
run("${CC}" ${flags} "${out}/dice.c" "${out}/maximum.c" ${link} -o "${app}")
run("${app}")
message(STATUS "roll: inferred IDs, ordering, sparse dispatch, plugins and route enforcement passed")
