/*
 * Dice Fine-Grained Dispatcher Generator
 *
 * This tool generates dispatcher templates for Dice modules with fine-grained control.
 * It supports generating:
 * 1. One file per chain that dispatches to a set of events
 * 2. One file per chain/event that dispatches to a set of slots
 *
 * This allows different chain-event-slot combinations to be configured independently.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <dirent.h>
#include <sys/stat.h>
#include <ctype.h>

// Structure to hold chain-event-slot configurations
typedef struct {
    char* chain;
    char* event;
    char* slot;
} chain_event_slot_t;

// Structure for configuration
typedef struct {
    char* type;  // main, chain, chain-event, slot
    char* output_dir;
    char** chains;
    char** events;
    char** slots;
    int chains_count;
    int events_count;
    int slots_count;
} dispatcher_config_t;

// Function to print usage information
void print_usage(const char* prog_name) {
    printf("Usage: %s [OPTIONS]\n", prog_name);
    printf("\nOptions:\n");
    printf("  --type TYPE          Type of dispatcher template to generate (main|chain|chain-event|slot)\n");
    printf("  --output-dir DIR     Output directory for generated files\n");
    printf("  --chains LIST        Comma-separated list of chain IDs\n");
    printf("  --events LIST        Comma-separated list of event IDs\n");
    printf("  --slots LIST         Comma-separated list of slot IDs\n");
    printf("  --help               Show this help message\n");
    printf("\nExamples:\n");
    printf("  %s --type main\n", prog_name);
    printf("  %s --type chain --chains 0,1,2\n", prog_name);
    printf("  %s --type chain-event --chains 0,1 --events 0,1,2\n", prog_name);
    printf("  %s --type slot --slots 0,1,2\n", prog_name);
}

// Helper function to split comma-separated strings
char** split_string(const char* str, int* count) {
    if (!str) {
        *count = 0;
        return NULL;
    }

    // Count commas to determine array size
    int num_items = 1;
    const char* ptr = str;
    while (*ptr) {
        if (*ptr == ',') num_items++;
        ptr++;
    }

    char** result = malloc((num_items + 1) * sizeof(char*));
    if (!result) return NULL;

    *count = num_items;

    char* temp = strdup(str);
    if (!temp) {
        free(result);
        return NULL;
    }

    char* token = strtok(temp, ",");
    int i = 0;
    while (token && i < num_items) {
        result[i] = strdup(token);
        // Trim whitespace
        while (*result[i] == ' ') result[i]++;
        char* end = result[i] + strlen(result[i]) - 1;
        while (end > result[i] && *end == ' ') *end-- = '\0';
        i++;
        token = strtok(NULL, ",");
    }
    result[i] = NULL;

    free(temp);
    return result;
}

// Helper function to free string array
void free_string_array(char** arr) {
    if (!arr) return;
    for (int i = 0; arr[i]; i++) {
        free(arr[i]);
    }
    free(arr);
}

// Function to create directory if it doesn't exist
int create_directory(const char* path) {
    struct stat st = {0};
    if (stat(path, &st) == -1) {
        return mkdir(path, 0755);
    }
    return 0;
}

// Function to sanitize filename (remove invalid characters)
void sanitize_filename(char* filename) {
    for (int i = 0; filename[i]; i++) {
        if (filename[i] == '/' || filename[i] == '\\' || filename[i] == ':' ||
            filename[i] == '*' || filename[i] == '?' || filename[i] == '"' ||
            filename[i] == '<' || filename[i] == '>' || filename[i] == '|') {
            filename[i] = '_';
        }
    }
}

// Simulated tmplr functionality for fine-grained generation
int simulate_tmplr_call(const char* template_file, const char* output_file,
                       const char** variables, const char** values, int var_count) {
    printf("Simulating tmplr call for %s:\n", output_file);
    printf("  Template: %s\n", template_file);
    printf("  Variables:\n");
    for (int i = 0; i < var_count; i++) {
        printf("    %s = %s\n", variables[i], values[i]);
    }
    printf("  (In a real implementation, this would call libtmplr functions)\n\n");

    // Create a dummy output file for demonstration
    FILE* f = fopen(output_file, "w");
    if (f) {
        fprintf(f, "/* Generated dispatcher code */\n");
        fprintf(f, "/* Template: %s */\n", template_file);
        fprintf(f, "/* Generated by Dice Fine-Grained Dispatcher Generator */\n");
        fprintf(f, "#include <dice/pubsub.h>\n\n");
        fprintf(f, "/* Generated dispatcher function for %s */\n", output_file);
        fprintf(f, "DICE_HIDE enum ps_err ps_dispatch_generated(const chain_id chain, const type_id type, void *event, struct metadata *md) {\n");
        fprintf(f, "    return PS_HANDLER_OFF;\n");
        fprintf(f, "}\n");
        fclose(f);
        return 0;
    }
    return -1;
}

// Generate one file per chain
int generate_per_chain(const char* output_dir, char** chains, int chains_count) {
    printf("Generating dispatcher files per chain...\n");

    for (int i = 0; i < chains_count; i++) {
        char filename[1024];
        char sanitized_chain[256];
        strncpy(sanitized_chain, chains[i], sizeof(sanitized_chain) - 1);
        sanitized_chain[sizeof(sanitized_chain) - 1] = '\0';
        sanitize_filename(sanitized_chain);

        snprintf(filename, sizeof(filename), "%s/dispatch_chain_%s.c", output_dir, sanitized_chain);

        printf("  Generating: %s\n", filename);

        // For demonstration, we'll just create a simple file
        FILE* f = fopen(filename, "w");
        if (f) {
            fprintf(f, "/* Chain dispatcher for %s */\n", chains[i]);
            fprintf(f, "#include <dice/pubsub.h>\n\n");
            fprintf(f, "/* Generated dispatcher for chain %s */\n", chains[i]);
            fprintf(f, "DICE_HIDE enum ps_err ps_dispatch_chain_%s(const chain_id chain, const type_id type, void *event, struct metadata *md) {\n", chains[i]);
            fprintf(f, "    return PS_HANDLER_OFF;\n");
            fprintf(f, "}\n");
            fclose(f);
        }
    }

    return 0;
}

// Generate one file per chain/event
int generate_per_chain_event(const char* output_dir, char** chains, int chains_count,
                            char** events, int events_count) {
    printf("Generating dispatcher files per chain/event...\n");

    for (int i = 0; i < chains_count; i++) {
        for (int j = 0; j < events_count; j++) {
            char filename[1024];
            char sanitized_chain[256];
            char sanitized_event[256];
            strncpy(sanitized_chain, chains[i], sizeof(sanitized_chain) - 1);
            sanitized_chain[sizeof(sanitized_chain) - 1] = '\0';
            sanitize_filename(sanitized_chain);

            strncpy(sanitized_event, events[j], sizeof(sanitized_event) - 1);
            sanitized_event[sizeof(sanitized_event) - 1] = '\0';
            sanitize_filename(sanitized_event);

            snprintf(filename, sizeof(filename), "%s/dispatch_chain_%s_event_%s.c",
                    output_dir, sanitized_chain, sanitized_event);

            printf("  Generating: %s\n", filename);

            // For demonstration, we'll just create a simple file
            FILE* f = fopen(filename, "w");
            if (f) {
                fprintf(f, "/* Chain-event dispatcher for %s/%s */\n", chains[i], events[j]);
                fprintf(f, "#include <dice/pubsub.h>\n\n");
                fprintf(f, "/* Generated dispatcher for chain %s, event %s */\n", chains[i], events[j]);
                fprintf(f, "DICE_HIDE enum ps_err ps_dispatch_chain_%s_event_%s(const chain_id chain, const type_id type, void *event, struct metadata *md) {\n",
                        chains[i], events[j]);
                fprintf(f, "    return PS_HANDLER_OFF;\n");
                fprintf(f, "}\n");
                fclose(f);
            }
        }
    }

    return 0;
}

// Generate one file per slot
int generate_per_slot(const char* output_dir, char** slots, int slots_count) {
    printf("Generating dispatcher files per slot...\n");

    for (int i = 0; i < slots_count; i++) {
        char filename[1024];
        char sanitized_slot[256];
        strncpy(sanitized_slot, slots[i], sizeof(sanitized_slot) - 1);
        sanitized_slot[sizeof(sanitized_slot) - 1] = '\0';
        sanitize_filename(sanitized_slot);

        snprintf(filename, sizeof(filename), "%s/dispatch_slot_%s.c", output_dir, sanitized_slot);

        printf("  Generating: %s\n", filename);

        // For demonstration, we'll just create a simple file
        FILE* f = fopen(filename, "w");
        if (f) {
            fprintf(f, "/* Slot dispatcher for %s */\n", slots[i]);
            fprintf(f, "#include <dice/pubsub.h>\n\n");
            fprintf(f, "/* Generated dispatcher for slot %s */\n", slots[i]);
            fprintf(f, "DICE_HIDE enum ps_err ps_dispatch_slot_%s(const chain_id chain, const type_id type, void *event, struct metadata *md) {\n", slots[i]);
            fprintf(f, "    return PS_HANDLER_OFF;\n");
            fprintf(f, "}\n");
            fclose(f);
        }
    }

    return 0;
}

// Parse command line arguments
int parse_arguments(int argc, char* argv[], dispatcher_config_t* config) {
    memset(config, 0, sizeof(dispatcher_config_t));

    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--help") == 0 || strcmp(argv[i], "-h") == 0) {
            print_usage(argv[0]);
            return 1; // Exit after showing help
        }
        else if (strcmp(argv[i], "--type") == 0 && i + 1 < argc) {
            config->type = argv[++i];
        }
        else if (strcmp(argv[i], "--output-dir") == 0 && i + 1 < argc) {
            config->output_dir = argv[++i];
        }
        else if (strcmp(argv[i], "--chains") == 0 && i + 1 < argc) {
            config->chains = split_string(argv[++i], &config->chains_count);
        }
        else if (strcmp(argv[i], "--events") == 0 && i + 1 < argc) {
            config->events = split_string(argv[++i], &config->events_count);
        }
        else if (strcmp(argv[i], "--slots") == 0 && i + 1 < argc) {
            config->slots = split_string(argv[++i], &config->slots_count);
        }
    }

    // Set default output directory
    if (!config->output_dir) {
        config->output_dir = ".";
    }

    // Set default type if not specified
    if (!config->type) {
        config->type = "main";
    }

    return 0;
}

// Cleanup function for arguments
void cleanup_config(dispatcher_config_t* config) {
    if (config->chains) {
        free_string_array(config->chains);
    }
    if (config->events) {
        free_string_array(config->events);
    }
    if (config->slots) {
        free_string_array(config->slots);
    }
}

int main(int argc, char* argv[]) {
    dispatcher_config_t config;

    // Parse command line arguments
    int result = parse_arguments(argc, argv, &config);
    if (result == 1) {
        return 0; // Help was shown, exit normally
    }
    if (result != 0) {
        fprintf(stderr, "Error parsing arguments\n");
        return 1;
    }

    // Create output directory if needed
    create_directory(config.output_dir);

    // Validate required arguments based on type
    if (strcmp(config.type, "chain") == 0 && !config.chains) {
        fprintf(stderr, "Error: --chains required for --type chain\n");
        cleanup_config(&config);
        return 1;
    }

    if (strcmp(config.type, "chain-event") == 0 && (!config.chains || !config.events)) {
        fprintf(stderr, "Error: --chains and --events required for --type chain-event\n");
        cleanup_config(&config);
        return 1;
    }

    if (strcmp(config.type, "slot") == 0 && !config.slots) {
        fprintf(stderr, "Error: --slots required for --type slot\n");
        cleanup_config(&config);
        return 1;
    }

    // Generate based on type
    int success = 0;

    if (strcmp(config.type, "main") == 0) {
        printf("Generating main dispatcher template...\n");
        // For main dispatcher, we'd generate the standard dispatch.c template
        // This is a simplified demonstration
        printf("  Main dispatcher generation (simplified)\n");
        success = 0;
    }
    else if (strcmp(config.type, "chain") == 0 && config.chains) {
        success = generate_per_chain(config.output_dir, config.chains, config.chains_count);
    }
    else if (strcmp(config.type, "chain-event") == 0 && config.chains && config.events) {
        success = generate_per_chain_event(config.output_dir, config.chains, config.chains_count,
                                          config.events, config.events_count);
    }
    else if (strcmp(config.type, "slot") == 0 && config.slots) {
        success = generate_per_slot(config.output_dir, config.slots, config.slots_count);
    }
    else {
        fprintf(stderr, "Error: Invalid type '%s'. Use 'main', 'chain', 'chain-event', or 'slot'\n", config.type);
        cleanup_config(&config);
        return 1;
    }

    if (success == 0) {
        printf("Successfully generated dispatcher templates in %s\n", config.output_dir);
    } else {
        fprintf(stderr, "Failed to generate dispatcher templates\n");
        success = 1;
    }

    cleanup_config(&config);
    return success;
}