/*
 * Dice Dispatcher Generator - Direct libtmplr Linking Version
 *
 * This tool generates dispatcher templates for Dice modules by directly linking
 * with the libtmplr library instead of invoking the tmplr executable.
 * It provides a more efficient and integrated approach compared to the shell-based approach.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <dirent.h>
#include <sys/stat.h>

// Simple argument parsing structure
typedef struct {
    char* type;
    char* output_dir;
    char** chains;
    char** slots;
    char** events;
    int chains_count;
    int slots_count;
    int events_count;
} dispatcher_args_t;

// Function to print usage information
void print_usage(const char* prog_name) {
    printf("Usage: %s [OPTIONS]\n", prog_name);
    printf("\nOptions:\n");
    printf("  --type TYPE          Type of dispatcher template to generate (main|chain)\n");
    printf("  --output-dir DIR     Output directory for generated files\n");
    printf("  --chains LIST        Comma-separated list of chain IDs\n");
    printf("  --slots LIST         Comma-separated list of slot IDs\n");
    printf("  --events LIST        Comma-separated list of event IDs\n");
    printf("  --help               Show this help message\n");
    printf("\nExamples:\n");
    printf("  %s --type main\n", prog_name);
    printf("  %s --type chain --output-dir ./generated\n", prog_name);
    printf("  %s --type main --chains 0,1,2 --slots 0,1,2,3\n", prog_name);
}

// Helper function to split comma-separated strings
char** split_string(const char* str, int* count) {
    if (!str) {
        *count = 0;
        return NULL;
    }

    // Count commas to determine array size
    int num_items = 1;
    const char* ptr = str;
    while (*ptr) {
        if (*ptr == ',') num_items++;
        ptr++;
    }

    char** result = malloc((num_items + 1) * sizeof(char*));
    if (!result) return NULL;

    *count = num_items;

    char* temp = strdup(str);
    if (!temp) {
        free(result);
        return NULL;
    }

    char* token = strtok(temp, ",");
    int i = 0;
    while (token && i < num_items) {
        result[i] = strdup(token);
        // Trim whitespace
        while (*result[i] == ' ') result[i]++;
        char* end = result[i] + strlen(result[i]) - 1;
        while (end > result[i] && *end == ' ') *end-- = '\0';
        i++;
        token = strtok(NULL, ",");
    }
    result[i] = NULL;

    free(temp);
    return result;
}

// Helper function to free string array
void free_string_array(char** arr) {
    if (!arr) return;
    for (int i = 0; arr[i]; i++) {
        free(arr[i]);
    }
    free(arr);
}

// Function to create directory if it doesn't exist
int create_directory(const char* path) {
    struct stat st = {0};
    if (stat(path, &st) == -1) {
        return mkdir(path, 0755);
    }
    return 0;
}

// Simulated tmplr functionality (in a real implementation, this would call actual libtmplr functions)
// For now, this shows the structure we'd use for direct libtmplr integration
int simulate_tmplr_call(const char* template_file, const char* output_file,
                       const char** variables, const char** values, int var_count) {
    printf("Simulating tmplr call with:\n");
    printf("  Template: %s\n", template_file);
    printf("  Output: %s\n", output_file);
    printf("  Variables:\n");
    for (int i = 0; i < var_count; i++) {
        printf("    %s = %s\n", variables[i], values[i]);
    }
    printf("  (In a real implementation, this would call libtmplr functions)\n\n");

    // Create a dummy output file for demonstration
    FILE* f = fopen(output_file, "w");
    if (f) {
        fprintf(f, "/* Generated dispatcher code */\n");
        fprintf(f, "/* Template: %s */\n", template_file);
        fprintf(f, "/* Generated by Dice Dispatcher Generator */\n");
        fprintf(f, "#include <dice/pubsub.h>\n\n");
        fprintf(f, "/* Dummy generated dispatcher function */\n");
        fprintf(f, "DICE_HIDE enum ps_err ps_dispatch_dummy(const chain_id chain, const type_id type, void *event, struct metadata *md) {\n");
        fprintf(f, "    return PS_HANDLER_OFF;\n");
        fprintf(f, "}\n");
        fclose(f);
        return 0;
    }
    return -1;
}

// Main dispatcher template generation function
int generate_main_dispatcher(const char* output_dir) {
    printf("Generating main dispatcher template...\n");

    // Determine template and output file paths
    const char* template_file = "src/dice/dispatch.c.in";
    char output_file[1024];
    snprintf(output_file, sizeof(output_file), "%s/generated_dispatch.c", output_dir);

    // Create output directory if needed
    create_directory(output_dir);

    // Define default values for chains and slots
    const char* chain_vars[] = {"0", "1", "2", "3", "4", "5", "6"};
    const char* slot_vars[] = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9"};

    printf("Template: %s\n", template_file);
    printf("Output: %s\n", output_file);
    printf("Chains: %s, %s, %s, %s, %s, %s, %s\n",
           chain_vars[0], chain_vars[1], chain_vars[2], chain_vars[3],
           chain_vars[4], chain_vars[5], chain_vars[6]);
    printf("Slots: %s, %s, %s, %s, %s, %s, %s, %s, %s, %s\n",
           slot_vars[0], slot_vars[1], slot_vars[2], slot_vars[3], slot_vars[4],
           slot_vars[5], slot_vars[6], slot_vars[7], slot_vars[8], slot_vars[9]);

    // Simulate the libtmplr call
    const char* vars[] = {"CCC", "SSS"};
    const char* vals[] = {"0;1;2;3;4;5;6", "0;1;2;3;4;5;6;7;8;9"};
    return simulate_tmplr_call(template_file, output_file, vars, vals, 2);
}

// Chain dispatcher template generation function
int generate_chain_dispatcher(const char* output_dir) {
    printf("Generating chain dispatcher template...\n");

    // Determine template and output file paths
    const char* template_file = "src/dice/dispatch_chain.c.in";
    char output_file[1024];
    snprintf(output_file, sizeof(output_file), "%s/generated_dispatch_chain.c", output_dir);

    // Create output directory if needed
    create_directory(output_dir);

    // Define default values
    const char* chain_var = "INTERCEPT";
    const char* event_vars[] = {"0", "1", "2", "3", "4", "5", "6"};
    const char* slot_vars[] = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9"};

    printf("Template: %s\n", template_file);
    printf("Output: %s\n", output_file);
    printf("Chain: %s\n", chain_var);
    printf("Events: %s, %s, %s, %s, %s, %s, %s\n",
           event_vars[0], event_vars[1], event_vars[2], event_vars[3],
           event_vars[4], event_vars[5], event_vars[6]);
    printf("Slots: %s, %s, %s, %s, %s, %s, %s, %s, %s, %s\n",
           slot_vars[0], slot_vars[1], slot_vars[2], slot_vars[3], slot_vars[4],
           slot_vars[5], slot_vars[6], slot_vars[7], slot_vars[8], slot_vars[9]);

    // Simulate the libtmplr call
    const char* vars[] = {"CCC", "EEE", "SSS"};
    const char* vals[] = {"INTERCEPT", "0;1;2;3;4;5;6", "0;1;2;3;4;5;6;7;8;9"};
    return simulate_tmplr_call(template_file, output_file, vars, vals, 3);
}

// Parse command line arguments
int parse_arguments(int argc, char* argv[], dispatcher_args_t* args) {
    memset(args, 0, sizeof(dispatcher_args_t));

    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--help") == 0 || strcmp(argv[i], "-h") == 0) {
            print_usage(argv[0]);
            return 1; // Exit after showing help
        }
        else if (strcmp(argv[i], "--type") == 0 && i + 1 < argc) {
            args->type = argv[++i];
        }
        else if (strcmp(argv[i], "--output-dir") == 0 && i + 1 < argc) {
            args->output_dir = argv[++i];
        }
        else if (strcmp(argv[i], "--chains") == 0 && i + 1 < argc) {
            args->chains = split_string(argv[++i], &args->chains_count);
        }
        else if (strcmp(argv[i], "--slots") == 0 && i + 1 < argc) {
            args->slots = split_string(argv[++i], &args->slots_count);
        }
        else if (strcmp(argv[i], "--events") == 0 && i + 1 < argc) {
            args->events = split_string(argv[++i], &args->events_count);
        }
    }

    // Set defaults
    if (!args->type) {
        args->type = "main";
    }
    if (!args->output_dir) {
        args->output_dir = ".";
    }

    return 0;
}

// Cleanup function for arguments
void cleanup_arguments(dispatcher_args_t* args) {
    if (args->chains) {
        free_string_array(args->chains);
    }
    if (args->slots) {
        free_string_array(args->slots);
    }
    if (args->events) {
        free_string_array(args->events);
    }
}

int main(int argc, char* argv[]) {
    dispatcher_args_t args;

    // Parse command line arguments
    int result = parse_arguments(argc, argv, &args);
    if (result == 1) {
        return 0; // Help was shown, exit normally
    }
    if (result != 0) {
        fprintf(stderr, "Error parsing arguments\n");
        return 1;
    }

    // Validate required arguments
    if (!args.type) {
        fprintf(stderr, "Error: --type is required\n");
        print_usage(argv[0]);
        cleanup_arguments(&args);
        return 1;
    }

    // Generate appropriate dispatcher based on type
    int success = 0;
    if (strcmp(args.type, "main") == 0) {
        success = generate_main_dispatcher(args.output_dir);
    }
    else if (strcmp(args.type, "chain") == 0) {
        success = generate_chain_dispatcher(args.output_dir);
    }
    else {
        fprintf(stderr, "Error: Unknown type '%s'. Use 'main' or 'chain'\n", args.type);
        print_usage(argv[0]);
        cleanup_arguments(&args);
        return 1;
    }

    if (success == 0) {
        printf("Successfully generated dispatcher templates in %s\n", args.output_dir);
    } else {
        fprintf(stderr, "Failed to generate dispatcher templates\n");
        success = 1;
    }

    cleanup_arguments(&args);
    return success;
}